---
- hosts: 127.0.0.1
  connection: local
  roles:
  - { role: ec2, region: 'us-west-2', instance_type: 't2.micro',
      compute_image: 'ami-5189a661', instance_tag_name: 'docker',
      keypair: 'john.bertrand.aws' }

- hosts: newinstances  
  name: install docker
  user: ubuntu
  sudo: true
  gather_facts: true

  roles:
  - common
  - docker

# vim:ft=ansible:
